### ISSUE TITLE
Items!

### ISSUE THREAD

**Issue by Regulator13** [famegames/fire-and-ice#39]
_This is a discussion thread. It can be closed when actions have been taken, such as the creation of new issues._

**Context** 
The game has some cool stuff but not enough cool stuff.

**Problem/idea**
Create some items to make the game more interesting, especially in single player. Also decide if they will spawn on specific platforms all the time like we currently have it or some other way.

**Example(s)**
I was thinking of individual, one time pickup energy and health potions. They would spawn each level and could maybe be picked up with the down arrow as opposed to collision. The players would have to use their energy wisely then at times instead of going back to the well.

Let me know what you think about that idea and more idea for items.

*Include any tags that apply. Tag a person if you are looking for a response from someone specific.*

**Comment by afrey15** [comment]
It is cool! I played the other day. I like the items that use energy to power! I like that you pick them up. I have thought about other things that may affect your jumping when you are holding them, like normal blocks, reducing jumping. This would be a good start to do that here.

**Comment by Regulator13** [comment]
Whoa, someone else in the team actually made a comment! What's next, the gamemaker throwing in his opinion?? Anyways you make a good point. The jetpacks manually reduce jumping height but we could make it so player's mass factors into their jumping and the items they're holding add to their mass. By doing this I could actually let player's jump with a jetpack on, but since it's so heavy they wouldn't be able to go very high. I like that a lot actually.

**Comment by afrey15** [comment]
Yup! Makes sense!

**Comment by Phabbits** [comment]
I think that it is very important to define what an item is before beginning to program for them. In my mind an item cannot both be a jet-pack and trampoline, since it would not make much sense to "equip" a trampoline. I believe that an item should be defined as something that you could pick up and it would replace your normal fire and ice functionality.

Based on the current setup of the game, I do not think that it would be a appropriate to add a multi-slot inventory, but could see the possibility of it in the future, with each item you pick up adding mass and making it harder for you to move. In this case I could see a team strategically dividing who picks up items along the way to ensure that every member can still make it to the top. We could start making the game more of a battle to the top with enemies and weapons then, rather than just beating the surrondings.

In any case, to keep our programming of items the as flexible as possible I think that we should define an item as an object that can be equipped and utilized instead of the normal fire and ice options. We could make unequipping the item scrolling of the middle mouse wheel, and this would also us to have any size inventory, and two ways to use each item. Picking up and dropping items could be the down key as Regulator13 suggested.

**Comment by Regulator13** [comment]
Well well look who we have here. I agree @Phabbits. Trampolines shouldn't have been included in this list, they aren't an item. I guess we can add the jetpack to an item class but I don't really forsee holding multiple items. Still, flexibility or whatever so we could give them an some item indication, although I'm not sure what that would be

**Comment by afrey15** [comment]
I'm interested in items being powered by fire and ice and I have another idea. We might severely reduce the firing distance of fire and ice to be a little puff that shoots out from the player and quickly fades away, as it already needed to be reduced. Another item could be a gun. It would shoot fire and ice in a nice straight line that would go a little further. I still think we would cap even the gun's range at 4-5 full size blocks.

**Comment by Regulator13** [comment]
I too like the fire and ice use of items, but I'm gonna disagree on the fireball range decrease. They do shoot far but I think this is necessary. I've played the game quite a bit recently and I think being able to hit lasers up high, freeze water droplets and water sources way above you, kill patrols, etc. is not just 'nice to be able to do' it's a necessity. Also I like the arc on the fireballs. Would recommend not changing

**Comment by Regulator13** [comment]
Any further item discussion will take place on the Dust team discussion page, closing this.
