### ISSUE TITLE
Water droplet does not wait for spawn animation

### ISSUE THREAD

**Issue by afrey15** [famegames/fire-and-ice#55]
**Describe the bug**
I created an animation that is supposed to play before the water drop starts falling but I do not know how to make the water droplet stay still

**To Reproduce**
1. Go to the branch "Austin"
2. Play the game and watch the droplets fall
3. They will look like they are forming and falling at the same time.

**Expected behavior**
At the least, the drop should not fall until it plays the animation. Maybe you should not be able to interact with it either. I would like someone to help walk me through this if possible.

**Comment by Regulator13** [comment]
Hey @afrey15. I'm unable to see any animation or animation sprite on your branch? I believe you must make a commit to make changes public, otherwise they'll only be available locally. If you don't want to make a commit until your issue is complete, I can discord when you have time and take a look at the issue.

**Comment by afrey15** [comment]
I have no problem making the commit! I figured I just needed to publish it! You should be able to test it when you get back
